-- CREATE DATABASE sales_example;

-- CREATE TABLE sales (
--     id INT PRIMARY KEY AUTO_INCREMENT,
--    -- id SERIAL PRIMARY KEY --POSTGRES,
--    date_created DATE DEFAULT (CURRENT_DATE),
--    date_fulfilled DATE,
--    customer_name VARCHAR(300) NOT NULL,
--    product_name VARCHAR(300) NOT NULL,
--    volume NUMERIC(10,3) NOT NULL CHECK(volume >= 0),
--    is_recurring BOOLEAN DEFAULT FALSE,
--    is_disputed BOOLEAN DEFAULT FALSE
-- );

-- INSERT INTO sales (
--     customer_name, 
--     product_name, 
--     volume
--     )
-- VALUES (
-- "VAIBHAV KATARIYA",
-- "IPhone-12",
-- 50000
-- );

-- INSERT INTO sales (
--     date_fulfilled,
--     customer_name, 
--     product_name, 
--     volume,
--     is_recurring,
--     is_disputed
--     )
-- VALUES (
-- "2022-05-06",  
-- "SIMRAN KATARIYA",
-- "Netflix",
-- 999,
-- TRUE,
-- FALSE
-- ),
-- (
-- "2022-05-06",  
-- "MEHER KATARIYA",
-- "AmazonPrime",
-- 1499,
-- TRUE,
-- TRUE
-- ),
-- (
-- NULL,
-- "SUNITA KATARIYA",
-- "FastTrack Watch",
-- 2500,
-- FALSE,
-- FALSE
-- );


-- INSERT INTO sales (
--   date_created,
--   date_fulfilled,
--   customer_name,
--   product_name,
--   volume,
--   is_disputed,
--   is_recurring
-- )
-- VALUES (
--   '2022-01-18',
--   '2022-03-11',
--   'Company A',
--   'A Nice Product',
--   489.99,
--   FALSE,
--   TRUE
-- ), (
--   '2022-01-18',
--   '2022-05-01',
--   'Company B',
--   'Video Game Collection',
--   3859.12,
--   FALSE,
--   FALSE
-- ), (
--   '2021-12-05',
--   NULL,
--   'Company C',
--   'Daily News Summary',
--   4.99,
--   FALSE,
--   TRUE
-- ), (
--   '2021-12-05',
--   '2021-12-07',
--   'Company A',
--   'Good-looking carpet',
--   1099.82,
--   TRUE,
--   FALSE
-- ), (
--   '2022-02-21',
--   '2022-02-24',
--   'Max Schwarz',
--   'Lord of the Rings Collection',
--   69.99,
--   FALSE,
--   FALSE
-- ), (
--   '2021-10-14',
--   '2022-02-21',
--   'Max Schwarz',
--   'Lord of the Rings Movies',
--   25.99,
--   FALSE,
--   FALSE
-- ), (
--   '2022-06-01',
--   NULL,
--   'Max Schwarz',
--   'Another book',
--   8.99,
--   FALSE,
--   FALSE
-- ), (
--   '2021-08-17',
--   '2021-09-12',
--   'Company D',
--   'Vehicle Services',
--   4999.99,
--   TRUE,
--   TRUE
-- ), (
--   '2021-03-12',
--   '2022-06-19',
--   'Company D',
--   'Vehicle Fleet',
--   280000,
--   FALSE,
--   FALSE
-- );

-- UPDATE sales
-- SET product_name = 'A TRUCK',
-- volume = volume * 1000
-- WHERE id = 13;

-- DELETE FROM sales
-- WHERE id = 13;

-- CREATE TABLE products (
--     id INT PRIMARY KEY AUTO_INCREMENT,
--     product_name VARCHAR(200) NOT NULL,
--     product_price NUMERIC(10,2) NOT NULL,
--     description TEXT NOT NULL,
--     amount_in_stock INT CHECK(amount_in_stock >= 0),
--     image_path VARCHAR(500)
-- );

-- DROP TABLE products;

-- ALTER TABLE products
-- MODIFY COLUMN product_price NUMERIC(10,2) NOT NULL CHECK(product_price>0);
